/* tslint:disable */
/* eslint-disable */
/**
 * let API - OpenAPI 3.0
 * A simple API for listing items for sale.  Some useful links: - [The GitHub repository](https://github.com/BeatsuDev/let)
 *
 * OpenAPI spec version: 1.0.0
 * Contact: vkbugge@hotmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface CreateUser
 */
export interface CreateUser {
    /**
     * 
     * @type {string}
     * @memberof CreateUser
     */
    email?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateUser
     */
    firstName?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateUser
     */
    lastName?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateUser
     */
    password?: string;
}
