/* tslint:disable */
/* eslint-disable */
/**
 * let API - OpenAPI 3.0
 * A simple API for listing items for sale.  Some useful links: - [The GitHub repository](https://github.com/BeatsuDev/let)
 *
 * OpenAPI spec version: 1.0.0
 * Contact: vkbugge@hotmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ListingMinimal } from "./listing-minimal";
/**
 *
 * @export
 * @interface InlineResponse200
 */
export interface InlineResponse200 {
  /**
   *
   * @type {Array<ListingMinimal>}
   * @memberof InlineResponse200
   */
  items?: Array<ListingMinimal>;
  /**
   *
   * @type {string}
   * @memberof InlineResponse200
   */
  next?: string;
  /**
   *
   * @type {string}
   * @memberof InlineResponse200
   */
  prev?: string;
  /**
   *
   * @type {number}
   * @memberof InlineResponse200
   */
  numberOfPages?: number;
  /**
   *
   * @type {number}
   * @memberof InlineResponse200
   */
  pageNumber?: number;
}
