/* tslint:disable */
/* eslint-disable */
/**
 * let API - OpenAPI 3.0
 * A simple API for listing items for sale.  Some useful links: - [The GitHub repository](https://github.com/BeatsuDev/let)
 *
 * OpenAPI spec version: 1.0.0
 * Contact: vkbugge@hotmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ListingMinimal } from "./listing-minimal";
import { Message } from "./message";
import { UserFull } from "./user-full";

/**
 *
 * @export
 * @interface ChatFull
 */
export interface ChatFull {
  /**
   *
   * @type {number}
   * @memberof ChatFull
   */
  id?: number;
  /**
   *
   * @type {UserFull}
   * @memberof ChatFull
   */
  seller?: UserFull;
  /**
   *
   * @type {UserFull}
   * @memberof ChatFull
   */
  buyer?: UserFull;
  /**
   *
   * @type {ListingMinimal}
   * @memberof ChatFull
   */
  listing?: ListingMinimal;
  /**
   *
   * @type {Array<Message>}
   * @memberof ChatFull
   */
  messages?: Array<Message>;
}
