/* tslint:disable */
/* eslint-disable */
/**
 * let API - OpenAPI 3.0
 * A simple API for listing items for sale.  Some useful links: - [The GitHub repository](https://github.com/BeatsuDev/let)
 *
 * OpenAPI spec version: 1.0.0
 * Contact: vkbugge@hotmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ListingMinimal } from "./listing-minimal";
import { Message } from "./message";
import { UserMinimal } from "./user-minimal";

/**
 *
 * @export
 * @interface ChatMinimal
 */
export interface ChatMinimal {
  /**
   *
   * @type {number}
   * @memberof ChatMinimal
   */
  id?: number;
  /**
   *
   * @type {UserMinimal}
   * @memberof ChatMinimal
   */
  buyer?: UserMinimal;
  /**
   *
   * @type {UserMinimal}
   * @memberof ChatMinimal
   */
  seller?: UserMinimal;
  /**
   *
   * @type {ListingMinimal}
   * @memberof ChatMinimal
   */
  listing?: ListingMinimal;
  /**
   *
   * @type {Message}
   * @memberof ChatMinimal
   */
  lastMessage?: Message;
}
