/* tslint:disable */
/* eslint-disable */
/**
 * let API - OpenAPI 3.0
 * A simple API for listing items for sale.  Some useful links: - [The GitHub repository](https://github.com/BeatsuDev/let)
 *
 * OpenAPI spec version: 1.0.0
 * Contact: vkbugge@hotmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Image } from "./image";
import { ListingState } from "./listing-state";
import { UserMinimal } from "./user-minimal";

/**
 *
 * @export
 * @interface ListingFull
 */
export interface ListingFull {
  /**
   *
   * @type {number}
   * @memberof ListingFull
   */
  id?: number;
  /**
   *
   * @type {string}
   * @memberof ListingFull
   */
  title?: string;
  /**
   *
   * @type {string}
   * @memberof ListingFull
   */
  summary?: string;
  /**
   *
   * @type {number}
   * @memberof ListingFull
   */
  price?: number;
  /**
   *
   * @type {Image}
   * @memberof ListingFull
   */
  thumbnail?: Image;
  /**
   *
   * @type {string}
   * @memberof ListingFull
   */
  locationName?: string;
  /**
   *
   * @type {string}
   * @memberof ListingFull
   */
  categoryName?: string;
  /**
   *
   * @type {string}
   * @memberof ListingFull
   */
  description?: string;
  /**
   *
   * @type {ListingState}
   * @memberof ListingFull
   */
  state?: ListingState;
  /**
   *
   * @type {Date}
   * @memberof ListingFull
   */
  created?: Date;
  /**
   *
   * @type {Array<Image>}
   * @memberof ListingFull
   */
  gallery?: Array<Image>;
  /**
   *
   * @type {UserMinimal}
   * @memberof ListingFull
   */
  seller?: UserMinimal;
}
