/* tslint:disable */
/* eslint-disable */
/**
 * let API - OpenAPI 3.0
 * A simple API for listing items for sale.  Some useful links: - [The GitHub repository](https://github.com/BeatsuDev/let)
 *
 * OpenAPI spec version: 1.0.0
 * Contact: vkbugge@hotmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ListingMinimal } from "./listing-minimal";
import { ListingState } from "./listing-state";
import { UserMinimal } from "./user-minimal";

/**
 *
 * @export
 * @interface ListingFull
 */
export interface ListingFull extends ListingMinimal {
  /**
   *
   * @type {string}
   * @memberof ListingFull
   */
  description?: string;
  /**
   *
   * @type {ListingState}
   * @memberof ListingFull
   */
  state?: ListingState;
  /**
   *
   * @type {Date}
   * @memberof ListingFull
   */
  created?: Date;
  /**
   *
   * @type {Array<string>}
   * @memberof ListingFull
   */
  galleryUrls?: Array<string>;
  /**
   *
   * @type {UserMinimal}
   * @memberof ListingFull
   */
  seller?: UserMinimal;
}
