/* tslint:disable */
/* eslint-disable */
/**
 * let API - OpenAPI 3.0
 * A simple API for listing items for sale.  Some useful links: - [The GitHub repository](https://github.com/BeatsuDev/let)
 *
 * OpenAPI spec version: 1.0.0
 * Contact: vkbugge@hotmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 *
 * @export
 * @interface ListingMinimal
 */
export interface ListingMinimal {
  /**
   *
   * @type {number}
   * @memberof ListingMinimal
   */
  id?: number;
  /**
   *
   * @type {string}
   * @memberof ListingMinimal
   */
  title?: string;
  /**
   *
   * @type {string}
   * @memberof ListingMinimal
   */
  summary?: string;
  /**
   *
   * @type {number}
   * @memberof ListingMinimal
   */
  price?: number;
  /**
   *
   * @type {string}
   * @memberof ListingMinimal
   */
  thumbnailUrl?: string;
  /**
   *
   * @type {string}
   * @memberof ListingMinimal
   */
  locationName?: string;
  /**
   *
   * @type {string}
   * @memberof ListingMinimal
   */
  categoryName?: string;
}
