/* tslint:disable */
/* eslint-disable */

/**
 * let API - OpenAPI 3.0
 * A simple API for listing items for sale.  Some useful links: - [The GitHub repository](https://github.com/BeatsuDev/let)
 *
 * OpenAPI spec version: 1.0.0
 * Contact: vkbugge@hotmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 *
 * @export
 * @interface UpdateUser
 */
export interface UpdateUser {
  /**
   *
   * @type {number}
   * @memberof UpdateUser
   */
  id?: number;
  /**
   *
   * @type {string}
   * @memberof UpdateUser
   */
  email?: string;
  /**
   *
   * @type {string}
   * @memberof UpdateUser
   */
  firstName?: string;
  /**
   *
   * @type {string}
   * @memberof UpdateUser
   */
  lastName?: string;
  /**
   *
   * @type {string}
   * @memberof UpdateUser
   */
  password?: string;
}
