/* tslint:disable */
/* eslint-disable */
/**
 * let API - OpenAPI 3.0
 * A simple API for listing items for sale.  Some useful links: - [The GitHub repository](https://github.com/BeatsuDev/let)
 *
 * OpenAPI spec version: 1.0.0
 * Contact: vkbugge@hotmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Location } from "./location";

/**
 *
 * @export
 * @interface UpdateListing
 */
export interface UpdateListing {
  /**
   *
   * @type {string}
   * @memberof UpdateListing
   */
  title?: string;
  /**
   *
   * @type {string}
   * @memberof UpdateListing
   */
  summary?: string;
  /**
   *
   * @type {string}
   * @memberof UpdateListing
   */
  description?: string;
  /**
   * Price in øre
   * @type {number}
   * @memberof UpdateListing
   */
  price?: number;
  /**
   *
   * @type {number}
   * @memberof UpdateListing
   */
  categoryId?: number;
  /**
   *
   * @type {Location}
   * @memberof UpdateListing
   */
  location?: Location;
  /**
   *
   * @type {number}
   * @memberof UpdateListing
   */
  thumbnailId?: number;
  /**
   *
   * @type {Array<number>}
   * @memberof UpdateListing
   */
  galleryIds?: Array<number>;
}
