name: lint

on:
  push:
    branches:
      - '*'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js environment
        uses: actions/setup-node@v2
        with:
          node-version: '18.x'
      - name: Install dependencies
        run: |
          cd frontend
          npm install
      - name: Lint with ESLint
        run: |
          cd frontend
          npx eslint --ext .js,.vue,.ts,.tsx .
      - name: Format with Prettier
        run: |
          cd frontend
          npx prettier --write '**/*.{js,vue,ts,tsx}'
